name: 'test'

on: workflow_call

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: build-dist
          path: packages/*/dist/**

  unit-test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - run: pnpm install

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-dist
          path: ./packages

      - name: Debug paths
        run: ls -R packages/cli

      - name: Run unit tests
        run: pnpm run test-unit

  unit-test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20, 22, 24]
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - run: pnpm install

      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-dist
          path: ./packages

      - name: Run unit tests
        run: pnpm run test-unit

  # e2e-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5

  #     - name: Setup cache for Chromium binary
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.cache/puppeteer
  #         key: chromium-${{ hashFiles('pnpm-lock.yaml') }}

  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v4.1.0

  #     - name: Install Node.js
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version-file: '.node-version'
  #         cache: 'pnpm'

  #     - run: pnpm install
  #     # - run: node node_modules/puppeteer/install.mjs

  #     - name: Run e2e tests
  #       run: pnpm run test-e2e

  lint-and-test-dts:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - run: pnpm install
      - run: pnpm build

      - name: Run eslint
        run: pnpm run lint

      - name: Run prettier
        run: pnpm run format-check

      - name: Run tsc
        run: pnpm run check

      - name: Run docs
        run: pnpm run docs-build

      # - name: Run type declaration tests
      #   run: pnpm run test-dts
